version: '3'
services: 
  preview: 
    build: "https://${GITHUB_TOKEN}:@github.com/${GITHUB_REPO}.git#rk-changelog-pro/changelog"
    ports:
      - 3000:3000
    volumes: 
      - ./assets:/app/apps/web/_content/assets
      - ./pages:/app/apps/web/_content/pages
    environment:
      - MODE=EDIT
      - GITHUB_TOKEN=${GITHUB_TOKEN}