matrix:
  - name: Python source
    sources:
      - docs/examples/**/*.py
    dictionary:
      wordlists:
      - .wordlist.txt
      output: docs/wordlist.dic
    encoding: utf-8
    pipeline:
      - pyspelling.filters.python:
  - name: markdown
    sources:
      - 'docs/**/*.md'
    dictionary:
      wordlists:
        - .wordlist.txt
      output: wordlist.dic
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          attributes:
          - title
          - alt
          ignores:
          - code
          - pre
      - pyspelling.filters.url:
