version: '3'
services:
  preview:
    build: "https://${GITHUB_TOKEN}:@github.com/${GITHUB_REPO}.git#dev"
    ports:
      - 3001:3001
    volumes:
      - ./assets:/app/apps/docs/_content/main/assets
      - ./pages:/app/apps/docs/_content/main/pages
      - ./examples:/app/apps/docs/_content/main/examples
      - ./index.yml:/app/apps/docs/_content/main/index.yml
      - ./api.yml:/app/apps/docs/_content/main/api.yml
      - ./versions.yml:/app/apps/docs/_content/main/versions.yml
    environment:
      - MODE=EDIT
      - GITHUB_TOKEN=${GITHUB_TOKEN}
