build: 
	docker-compose build
up: 
	docker-compose up
test: # run the tests on the examples directory
	echo "Not Implemented Yet!"
check: # here we can check validity of markdown, enforce our own rules e.g. only one <h1> as the first element, run prettier on .md/.mdx etc. 
	echo "Not Implemented Yet!"