name: Docsearch Scraper
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update-docsearch:
    runs-on: depot-ubuntu-22.04
    steps:
      # Check out latest code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update DocSearch
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
        run: docker run --env ALGOLIA_APP_ID=$ALGOLIA_APP_ID --env ALGOLIA_API_KEY=$ALGOLIA_API_KEY -e "CONFIG=$(cat ./docs/algolia.config.json | jq -r tostring)" algolia/docsearch-scraper