name: Content Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the client repository
        uses: actions/checkout@v3

      - name: Checkout the turbo repository
        uses: actions/checkout@v3
        with:
          repository: fennel-ai/turbo
          token: ${{ secrets.TURBO_TOKEN }}
          path: turbo

      - name: Copy docs folder to turbo repo
        run: |
          mkdir -p turbo/apps/docs/_content
          cp -r docs/* turbo/apps/docs/_content/

      - name: Install pnpm and turbo
        run: |
          npm i -g pnpm
          npm i -g turbo

      - name: Install dependencies
        run: |
          cd turbo
          pnpm install --frozen-lockfile --reporter=ndjson

      - name: Set environment variable and build
        env:
          MODE: EDIT
        run: |
          cd turbo/apps/docs
          NODE_OPTIONS="--trace-warnings" pnpm run build
