name: Content Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the client repository
        uses: actions/checkout@v3

      - name: Checkout the turbo repository
        uses: actions/checkout@v3
        with:
          repository: fennel-ai/turbo
          token: ${{ secrets.TURBO_TOKEN }}
          ref: rk/test-link-checking
          path: turbo

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: |
          cd turbo
          pnpm install --frozen-lockfile --reporter=ndjson

      - name: Set environment variable and build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        run: |
          cd turbo/apps/docs
          touch .env
          echo HEAD_REF=$GITHUB_HEAD_REF >> .env
          echo GITHUB_TOKEN=$TURBO_TOKEN >> .env
          cat .env
          cd ../../ && pnpm turbo run build --filter docs
          
