name: Content Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the client repository
        uses: actions/checkout@v3

      - name: Checkout the turbo repository
        uses: actions/checkout@v3
        with:
          repository: fennel-ai/turbo
          token: ${{ secrets.TURBO_TOKEN }}
          path: turbo

      - name: Copy docs folder to turbo repo
        run: |
          mkdir -p turbo/apps/docs/_content
          cp -r docs/* turbo/apps/docs/_content/

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: |
          cd turbo
          pnpm install --frozen-lockfile --reporter=ndjson

      - name: Set environment variable and build
        run: |
          cd turbo
          MODE='"EDIT"' pnpm turbo run build --filter docs
          
