name: Content Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the client repository
        uses: actions/checkout@v3

      - name: Checkout the turbo repository
        uses: actions/checkout@v3
        with:
          repository: fennel-ai/turbo
          token: ${{ secrets.TURBO_TOKEN }}
          path: turbo

      - name: Copy docs folder to turbo repo
        run: |
          mkdir -p turbo/apps/docs/_content
          cp -r docs/* turbo/apps/docs/_content/

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          cd turbo
          pnpm install --frozen-lockfile --reporter=ndjson

      - name: Set environment variable and build
        env:
          MODE: EDIT
        run: |
          cd turbo/apps/docs
          NODE_OPTIONS="--trace-warnings" pnpm run build
