name: Lints and Typecheck

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Lints and typecheck
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install packages
        run: pip install "flake8>=4.0.1" "black>=22.6.0" "mypy>=0.961"
      - name: flake8 lint
        run: flake8 .
      - name: black lint
        run: black --diff --check .
      - name: mypy typechecking
        run: mypy .